
version: "3.8"

services:
  react-mobi:
    build:
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./public:/react-mobi/public
      - ./src:/react-mobi/src

